Split the unconditional runtime requirements into extras
ansible/awx-plugins pull request #52
Opened 2024-10-29 21:09 UTC by jessicamack

All the runtime dependencies of `awx-plugins-core` are unconditional now. To take into account being able to depend only on certain plugins, I've split them into optional ones.

2024-10-30 02:48 UTC, webknjaz commented
@jessicamack to fix the CI, change `pyproject.toml` to `pyproject.toml --all-extras` on these lines: https://github.com/ansible/awx-plugins/blob/c7fc0a1/.github/workflows/pip-tools.yml#L102-L128. Also, here https://github.com/ansible/awx-plugins/blob/c7fc0a1/tox.ini#L15, after `deps =`, add `extras =` with a column containing all the extras, one per line, use two-space indents.

2024-10-30 02:48 UTC, webknjaz commented on pyproject.toml
> +# dependencies = [  # runtime deps  # https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-optional-dependencies
Keep the empty list declared instead of commenting this out.

2024-10-30 14:50 UTC, webknjaz commented
@jessicamack have you seen https://github.com/ansible/awx-plugins/pull/52#issuecomment-2445712910?

2024-10-30 18:59 UTC, djyasin approved these changes

2024-10-31 03:04 UTC, webknjaz commented
UPD: this is failing because of a bug in tox which is blocking the PR.

2024-11-02 00:52 UTC, webknjaz requested changes, later dismissed
@jessicamack so I learned that [PEP 685](https://packaging.python.org/en/latest/specifications/core-metadata/#provides-extra-multiple-use) will make the format of extras stricter in the internal core packaging metadata version 2.3. The user-facing extra names might still be allowed to be non-normalized. But in general, it's best to just follow that format to avoid confusion. Evidently, some tools are going to get confused and hit corner cases if we don't do this.

Action items:
* [x] Change extra names in `pyproject.toml` to have `-` instead of `_`
* [x] Change extra names in `tox.ini` to have `-` instead of `_`

2024-11-02 00:52 UTC, webknjaz commented on pyproject.toml
> +credentials-hashivault_kv = [
Example:
```suggestion
credentials-hashivault-kv = [
```

2024-11-02 00:52 UTC, webknjaz commented on tox.ini
> +  credentials-hashivault_kv
Example:
```suggestion
  credentials-hashivault-kv
```

2024-11-02 00:52 UTC, webknjaz commented on tox.ini
> +extras = {[testenv:build-docs]extras}
revert
```suggestion
```

2024-11-02 00:52 UTC, webknjaz commented on tox.ini
> +extras = {[testenv:build-docs]extras}
revert
```suggestion
```

2024-11-02 00:52 UTC, webknjaz commented on tox.ini
> +extras = {[testenv:build-docs]extras}
revert
```suggestion
```

2024-11-02 00:52 UTC, webknjaz commented on tox.ini
> +extras = {[testenv:build-docs]extras}
revert
```suggestion
```

2024-11-02 00:52 UTC, webknjaz commented on tox.ini
> +extras = {[testenv]extras}
revert
```suggestion
```

2024-11-04 21:25 UTC, webknjaz commented
@chrismeyersfsu could you confirm that the extra names look fine? Not that they can't be changed, but it's a chance to update them if there's anything obvious that stands out.

2024-11-05 15:08 UTC, webknjaz approved these changes
Waiting from Chris' take on the name, and then we can merge.

2024-11-06 09:07 UTC, chrismeyersfsu commented
So I understand, after this merges, awx will NOT get these extra modules unless it adds the [extras] optional directive I.e. awx-plugins.interfaces[extras] ?

2024-11-06 10:10 UTC, webknjaz commented
Yes. Although, it could just start depending on the version you released on Monday until things settle and they those extras that remain post split activities would need to be listed along with the version bump.

2024-11-06 10:34 UTC, chrismeyersfsu approved these changes

2024-11-06 11:20 UTC, merged

2024-11-06 11:21 UTC, webknjaz commented
Now a companion dep update is needed in awx.